// ** Exports
export {
  mergeBridgeUIComponents,
  mergeBridgeUIGlobal,
  resolveBridgeUIOptions,
} from "@core/Config/merge";
export { BRIDGE_UI_DEFAULT_GLOBAL } from "@core/Config/types";
export type {
  AlertConfigBase,
  AlertConfigOverrides,
  AvatarConfigBase,
  AvatarConfigOverrides,
  BadgeConfigBase,
  BadgeConfigOverrides,
  BridgeUIComponentsConfig,
  BridgeUIGlobal,
  BridgeUIOptions,
  ButtonConfigBase,
  ButtonConfigOverrides,
  CardConfigBase,
  CardConfigOverrides,
  CheckboxConfigBase,
  CheckboxConfigOverrides,
  Direction,
  IconConfigBase,
  IconConfigOverrides,
  LinkConfigBase,
  LinkConfigOverrides,
  MenuConfigBase,
  MenuConfigOverrides,
  ModalConfigBase,
  ModalConfigOverrides,
  NumberInputConfigBase,
  NumberInputConfigOverrides,
  PasswordInputConfigBase,
  PasswordInputConfigOverrides,
  RadioConfigBase,
  RadioConfigOverrides,
  SelectConfigBase,
  SelectConfigOverrides,
  TextInputConfigBase,
  TextInputConfigOverrides,
  TextareaConfigBase,
  TextareaConfigOverrides,
  ToggleConfigBase,
  ToggleConfigOverrides,
} from "@core/Config/types";
